spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
            - name: /customers/**
        - id: r2
          uri: http://localhost:8082
          predicates: 
            - name: /inventory/**    
          
            
      
      